name: Deploy Application

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install Dependencies
      run: npm install

    - name: Build Application
      run: npm run build

    - name: Set Environment Variable for SheetDB API
      run: echo "REACT_APP_SHEETDB_API_URL=${{ secrets.SHEETDB_API_URL }}" >> $GITHUB_ENV

    - name: Deploy Application
      run: npm run deploy
      env:
        REACT_APP_SHEETDB_API_URL: ${{ secrets.SHEETDB_API_URL }}
