name: Deploy Application

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install Dependencies
      run: npm install
      working-directory: app  # Adjust to your app's directory

    - name: Build Application
      env:
        REACT_APP_SHEETDB_API_URL: ${{ secrets.SHEETDB_API_URL }}
      run: npm run build
      working-directory: app  # Adjust to your app's directory

    - name: Deploy Application
      run: npm run deploy
      working-directory: app  # Adjust to your app's directory
